master:
    is_main_robot: false
    control_panel_active_high: true
    electron_uwb_mac: 42
    robot_size_x_mm: 260 # Robot diameter
    robot_alignment_length_mm: 135 # robot length from center to alignement border
    opponent_size_x_mm_default: 400
    calibration_direction: 1 # calibration side is on the front
    odometry:
        external_encoder_ticks_per_mm: 162.
        external_track_mm: 212.
        left_wheel_correction_factor: -1.
        right_wheel_correction_factor: 1.
    beacon:
        reflector_radius: 0.04 # in meters
        angular_offset: 0. # in radians
    aversive:
        control:
            angle:
                kp: 1.
                ki: 0.
                kd: 30.
                i_limit: 10.
            distance:
                kp: 0.1
                ki: 0.
                kd: 30.
                i_limit: 10.
        trajectories:
            angle:
                speed: # in rad / s
                    init: 0.75
                    slow: 0.75
                    fast: 3.
                acceleration: # in rad / s^2
                    init: 1.57
                    slow: 1.57
                    fast: 10.
            distance:
                speed: # in m / s
                    init: 0.5
                    slow: 0.2
                    fast: 0.5
                acceleration: # in m / s^2
                    init: 1.5
                    slow: 0.5
                    fast: 1.5
            windows:
                distance: 100.
                angle: 1.
                angle_start: 40.
actuator:
    left-wheel:
        encoders:
          primary:
            p: 49
            q: 676
            ticks_per_rev: 4096
        motor:
            torque_cst: 1.
        control:
            mode: 2
            current:
                kp: 4.
                ki: 1500.
                kd: 0.
                i_limit: 50.
            velocity:
                kp: 20.
                ki: 50.
                kd: 0.
                i_limit: 1000.
            position:
                kp: 0.1
                ki: 0.5
                kd: 0.
            low_batt_th: 5.
            acceleration_limit: 200.
            velocity_limit: 50.
            torque_limit: 30.
    right-wheel:
        encoders:
          primary:
            p: 49
            q: 676
            ticks_per_rev: 4096
        motor:
            torque_cst: 1.
        control:
            mode: 2
            current:
                kp: 4.
                ki: 1500.
                kd: 0.
                i_limit: 50.
            velocity:
                kp: 20.
                ki: 50.
                kd: 0.
                i_limit: 1000.
            position:
                kp: 0.1
                ki: 0.5
                kd: 0.

            low_batt_th: 5.
            acceleration_limit: 200.
            velocity_limit: 50.
            torque_limit: 30.
